# Generated by Django 5.2.11 on 2026-02-09 01:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('commune', models.CharField(blank=True, max_length=100)),
                ('nin', models.CharField(blank=True, help_text="Numéro d'identité nationale (18 chiffres)", max_length=18, null=True, unique=True)),
                ('ccp_or_passport', models.CharField(blank=True, help_text='CCP ou autre identifiant si pas de NIN', max_length=20, null=True)),
                ('aid_type', models.CharField(choices=[('colis-alimentaire', 'Colis alimentaire'), ('aide-financiere', 'Aide financière'), ('vetements', 'Vêtements'), ('produits-hygiene', "Produits d'hygiène"), ('medicaments', 'Médicaments'), ('autre', 'Autre')], max_length=30)),
                ('distribution_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('fullname', models.CharField(blank=True, max_length=255)),
                ('organisation', models.CharField(choices=[('croissant-rouge', 'Croissant Rouge'), ('kafil-el-yatim', 'Kafil El Yatim'), ('elbaraka', 'Association El Baraka'), ('other', 'Autre')], max_length=20)),
                ('is_admin', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
    ]
