# Generated by Django 5.2.11 on 2026-02-09 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_distribution_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distribution',
            name='nin',
            field=models.CharField(blank=True, help_text="Numéro d'identité nationale (18 chiffres)", max_length=18, null=True),
        ),
    ]
